### ISSUE TITLE
Pas d'encours pour le mois de Janvier 2017 DIR Centre Est

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/Reporting-FleetOne#2]
Pour constater

Login norbert.harchen@developpement-durable.gouv.fr
mot de passe : harchen
état reporting financier / Bilan financier

Filtre 2017 mois Janvier

résultat 2624.83 €

en pièce jointe l'extraction sur le CEI Dardilly = 3266.88 €

[Encours DIR CE janvier 2017.xlsx](https://github.com/groupe-gac/Reporting-FleetOne/files/783433/Encours.DIR.CE.janvier.2017.xlsx)

Exemple la visite 839815 qui est en statut facturée n'est pas dans le reporting

**Comment by AlainPierreSDPV** [comment]
prendre la visite 840938

**Comment by AlainPierreSDPV** [comment]
Je constate après la correction de Jacques que le reporting Bilan financier est conforme mais 
les 2 visites 841111 et 842570 qui ne sont pas encore facturées ne ressortent pas dans la requête travaux en cours non facturées

**Comment by meillere** [comment]
C'est réglé
