### ISSUE TITLE
anomalie d'affichage pour la page http://rep.gestionparc.com/full/Alertes.aspx

### ISSUE THREAD

**Issue by AlainPierreSDPV** [groupe-gac/Reporting-FleetOne#4]
à titre d'exemple prendre le client id = 15845 
login:  jeanrobert.GROSHENRY@ville-noisylegrand.fr
PW; noisy
à partir du tableau de bord du client
demander l'affichage du tableau "Règlementaire"  
choisir toutes à 1 mois et charger les données
Constater que les alertes réglementaires n'apparaissent pas

**Comment by meillere** [comment]
C'est corrigé
